### ISSUE TITLE
Icons missing for alerts

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/discourse-theme#10]
Without icons, I can't tell whether alerts are for replies, hearts, marking a solution, or @-ing.
![image](https://user-images.githubusercontent.com/6234475/73395020-eeae8400-429b-11ea-8dea-221cef3f5f4a.png)

**Comment by ahmadabdolsaheb** [comment]
Thanks for reporting this @ArielLeslie, the fix will be in production today.
