### ISSUE TITLE
Borders around online users' icons creates weird alignment

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/discourse-theme#7]
This is purely cosmetic, but changing the user icons from round to square has some odd effects. When a user has a border around their icon (I believe this happens if they are currently online), the user icons do not appear to be aligned.
![image](https://user-images.githubusercontent.com/6234475/73373736-5520ab80-4276-11ea-839a-c597d38bfb8f.png)

Also notice that if a user uploaded a round or rectangular image for their icon, it is not cropped to a square. 
![image](https://user-images.githubusercontent.com/6234475/73373961-a92b9000-4276-11ea-96c0-9116e4db2f48.png)

**Comment by ahmadabdolsaheb** [comment]
Thanks for pointing this out @ArielLeslie.
I added a mid-gray background to images so it would cover the transparency they have in their images and fixed the border issue.
